---
- name: Check if old WAR file exists
  stat:
    path: /home/tomcat1/apache-tomcat-10.1.31/webapps/*.war
  register: war_file_check

- name: take the backup of old war
  copy:
    src: /home/tomcat1/apache-tomcat-10.1.31/webapps/*.war
    dest: /home/tomcat1/apache-tomcat-10.1.31/webapps/backup
    remote_src: yes
  when: war_file_check.stat.exists 
