---
# tasks file for back_up_war_file

- name: Ensure the backup directory exists
  ansible.builtin.file:
    path: /home/tomcat1/apache-tomcat-10.1.31/webapps/backup
    state: directory

- name: Find the WAR file in the webapps directory
  ansible.builtin.find:
    paths: /home/tomcat1/apache-tomcat-10.1.31/webapps
    patterns: 'SimpleWebApplication-*.war'
    recurse: yes
  register: war_file

- name: Check if any file is found
  debug:
    msg: "Found WAR file: {{ war_file.files[0].path }}"
  when: war_file.matched > 0

- name: Take backup of the previous version application
  ansible.builtin.copy:
    src: "{{ war_file.files[0].path }}"
    dest: "/home/tomcat1/apache-tomcat-10.1.31/webapps/backup/"
    remote_src: yes
  when: war_file.matched > 0

- name: Display message if no WAR file is found
  debug:
    msg: "No WAR file found in the webapps directory."
  when: war_file.matched == 0

