---
- name: Fetch maven-metadata.xml content from Nexus
  uri:
    url: "http://13.126.68.188:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/maven-metadata.xml"
    method: GET
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
  register: metadata_content

- name: Save the content to a temporary file
  copy:
    content: "{{ metadata_content.content }}"
    dest: /tmp/maven-metadata.xml

- name: Extract latest version from maven-metadata.xml using shell command
  shell: "grep '<value>' /tmp/maven-metadata.xml | sed -e 's/.*<value>\\(.*\\)<\\/value>/\\1/'"
  register: version_output

- name: Display the latest version extracted
  debug:
    msg: "Latest Artifact Version: {{ version_output.stdout }}"

- name: Clean up temporary file
  file:
    path: /tmp/maven-metadata.xml
    state: absent
- name: Download WAR from Nexus
  get_url:
    url: "http://13.126.68.188:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/SimpleWebApplication-{{ Latest Artifact Version }}.war"
    dest: /home/tomcat1/apache-tomcat-10.1.31/webapps/
    mode: 0755
    owner: tomcat1
    group: tomcat1
    username: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
  register: download_war
