---
- name: Download war from nexus
  #shell: curl -u admin:admin -O http://13.235.23.234:8081/repository/maven-snapshots/com/maven/SimpleWebApplication'/1.0.0-SNAPSHOT/SimpleWebApplication'-1.0.0-20241018.135913-1.war
  get_url:
    url: "{{ war_url }}"
    dest: /home/tomcat1/apache-tomcat-10.1.31/webapps/
    mode: 0755
    owner: tomcat1
    group: tomcat1
    username: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
  register: download_war
