---
- name: Fetch maven-metadata.xml content from Nexus
  uri:
    url: "http://13.126.68.188:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/maven-metadata.xml"
    method: GET
    user: "{{ nexus_username }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
  register: metadata_content

- name: Debug the content of maven-metadata.xml
  debug:
    msg: "{{ metadata_content.content }}"

- name: Extract the latest version from maven-metadata.xml using regex
  set_fact:
    latest_version: "{{ (metadata_content.content | regex_search('<value>(.*?)</value>')) | first | default('No version found') }}"

- name: Debug the latest version
  debug:
    msg: "Latest Artifact Version: {{ latest_version }}"
