---
- name: Playbook to copy Apache Tomcat directory
  hosts: jenkins_server
  become: yes  # The user on the target servers
  become_user: root  # Use this if you want to escalate to root (default)
  vars: 
    ansible_ssh_timeout: 600
  roles:
    # - copying_apachefile
    # - tomcat_unitfile
    #- tomcat_dr
    #- tomcat_enable
    #- tomcat_start
    - tomcat_stop
    - back_up_war_file
    - move_war_file
    - tomcat_start
    #- latest_version

