---
- name: Playbook to create a file
  hosts: jenkins_server
  become_user: tomcat1  # The user on the target servers
  become: true           # Use this if you want to escalate to root (default)
  roles: 
    - copying_apachefile
  tasks:
    - name: Create a file
      file:
        path: /home/worker1/file1
        state: touch
    - name: Create a multiple file
      file: 
        path: '{{item}}'
        state : touch
        mode: 654
      with_items:
      - '/home/worker1/file2'
      - '/home/worker1/file3'
      - '/home/worker1/file4'
    - name: Install Maven
      yum:
        name: maven
        state: present
      become_user: root
    - name: Install Java
      yum: 
        name: java-17-amazon-corretto-devel
        state: present
      become_user: root
